name: Delete Files

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Remove files
        run: |
          git rm -rf packs/artificer-class.db
          git rm -rf packs/necrosteel-beasts.db
          git commit -m "Remove old DB files"
          git push
